/**
 * Golden-file tests against REAL (anonymized) İş Bankası statements.
 *
 * isbank-2026-06 is the deep golden fixture: the adapter's full output is
 * compared against isbank-2026-06.expected.json, which was generated by an
 * independent text-regex implementation (scripts/gen-expected-isbank.ts)
 * and reviewed by hand. The other five months assert the hard invariants:
 * perfect reconciliation and zero unparsed lines.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { TextItem } from '@/pdf/types';

import { isbankAdapter } from '../isbank';
import { reconcileStatement } from '../reconcile';

const PUBLIC_DIR = join(__dirname, '..', '..', '..', 'fixtures', 'public');

function loadFixture(name: string): TextItem[] {
  const raw = readFileSync(join(PUBLIC_DIR, `${name}.txt`), 'utf8');
  return raw
    .trim()
    .split('\n')
    .map((line) => JSON.parse(line) as TextItem);
}

const GOLDEN = 'isbank-2026-06';
const ALL_MONTHS = [
  'isbank-2026-02',
  'isbank-2026-03',
  'isbank-2026-04',
  'isbank-2026-05',
  'isbank-2026-06',
  'isbank-2026-07',
];

describe('isbankAdapter.detect', () => {
  it.each(ALL_MONTHS)('detects %s', (name) => {
    expect(isbankAdapter.detect(loadFixture(name))).toBe(true);
  });

  it('rejects unrelated documents', () => {
    const items: TextItem[] = [
      {
        str: 'GARANTİ BBVA KREDİ KARTI EKSTRESİ',
        x: 10,
        y: 10,
        width: 200,
        height: 10,
        pageIndex: 0,
        fontName: '',
        pageWidth: 595,
        pageHeight: 842,
      },
    ];
    expect(isbankAdapter.detect(items)).toBe(false);
  });
});

describe(`isbankAdapter golden file: ${GOLDEN}`, () => {
  const expected = JSON.parse(readFileSync(join(PUBLIC_DIR, `${GOLDEN}.expected.json`), 'utf8'));
  const parsed = isbankAdapter.parse(loadFixture(GOLDEN));

  it('matches the expected output exactly', () => {
    expect(parsed).toEqual(expected);
  });

  it('reconciles to the kuruş', () => {
    const result = reconcileStatement(parsed);
    expect(result.ok).toBe(true);
    expect(result.deltaKurus).toBe(0);
  });

  it('found the installment rows with their positions', () => {
    const installments = parsed.transactions.filter((t) => t.installmentNo !== null);
    expect(installments).toEqual([
      expect.objectContaining({
        rawDescription: expect.stringContaining('NIKE RETAIL'),
        amount: 115283,
        installmentNo: 2,
        installmentTotal: 3,
      }),
      expect.objectContaining({
        rawDescription: expect.stringContaining('MEDIAMARKT'),
        amount: 56581,
        installmentNo: 3,
        installmentTotal: 3,
      }),
    ]);
  });

  it('kept payments negative and purchases positive', () => {
    const payments = parsed.transactions.filter((t) =>
      t.rawDescription.includes('HESAPTAN AKTARIM'),
    );
    expect(payments.length).toBeGreaterThan(20);
    expect(payments.every((t) => t.amount < 0)).toBe(true);

    const spotify = parsed.transactions.find((t) => t.rawDescription.includes('SPOTİFY'));
    expect(spotify).toMatchObject({ txnDate: '2026-05-24', amount: 5500 });
  });
});

describe('isbankAdapter invariants across all six real months', () => {
  it.each(ALL_MONTHS)('%s: full reconciliation, zero unparsed lines', (name) => {
    const parsed = isbankAdapter.parse(loadFixture(name));

    expect(parsed.statementDate).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    expect(parsed.dueDate).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    expect(parsed.totalAmount).not.toBeNull();
    expect(parsed.previousBalance).not.toBeNull();
    expect(parsed.cardLast4).toMatch(/^\d{4}$/);
    expect(parsed.transactions.length).toBeGreaterThan(10);

    // The golden rule, applied to every known real statement.
    expect(parsed.unparsedLines).toEqual([]);
    const result = reconcileStatement(parsed);
    expect(result).toMatchObject({ ok: true, deltaKurus: 0 });
  });
});
